### ISSUE TITLE
Hi ,I hope you can help me solve a problem,thx

### ISSUE THREAD

**Issue by dlyldxwl** [weichengkuo/DeepBox#9]
Hi,
I find you do the full object detection of fast Deepbox +fast-rcnn in section 4.8 of your paper, but I don't know how to do to make deepbox as  a  method of get proposal to finish object detection in fast-rcnn， also ,I don't find the issue in READ ME . I am starting DL no longer,I hope you can help me ,thx！

**Comment by weichengkuo** [comment]
To set up a object detector with DeepBox, you'll need to download Edgeboxes first, and then run DeepBox on it to re-rank the proposals. Finally, you feed those proposals to Fast-RCNN.
